### ISSUE TITLE
パン = pao

### ISSUE THREAD

**Issue by elmimmo** [polm/cutlet#19] opened 2020-11-17 05:50 UTC
パン is transcribed as pao which I would say is wrong in any romanization system

**Comment by polm** [comment] 2020-11-17 06:16
This is due to the foreign spelling feature. パン for "bread" is generally considered to come from the Portuguese "pao", so this is not an error. This is the same feature that converts "カツ" to "cutlet". 

If you do not want this feature you can turn it off by setting `use_foreign_spelling` to False as demonstrated in the README. If you want to override パン specifically you can add an exception for it.

**Comment by polm** [comment] 2020-11-18 09:17
Closing since this is not a bug.

**Closed by polm** 2020-11-18 09:17 UTC
